name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose
        env:
          SKIP_PREFLIGHT_CHECK: true

      - name: Publish
        run: node common/scripts/install-run-rush.js publish -a -p
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
